selenium_demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selenium_demo/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView  # noqa
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

selenium_demo/models.py
# coding: utf-8

selenium_demo/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username

selenium_demo/users/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

selenium_demo/users/views.py
# -*- coding: utf-8 -*-
# Import the reverse lookup function
from django.core.urlresolvers import reverse

# view imports
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.views.generic import ListView

# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin

# Import the form from users/forms.py
from .forms import UserForm

# Import the customized User model
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

selenium_demo/templates/avatar/add.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

selenium_demo/templates/avatar/avatar_tag.html
<img src="{{ url }}" width="{{ size }}" height="{{ size }}" class="img-thumbnail">

selenium_demo/templates/avatar/base.html
{% extends "base.html" %}

{% block title %}django-avatar{% endblock %}
{% block content %}{% endblock %}

selenium_demo/templates/avatar/change.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% else %}
            <form method="POST" action="{% url 'avatar_change' %}">
                <ul>
                    {{ primary_avatar_form.as_ul }}
                </ul>
                <p>{% csrf_token %}<input type="submit" value="{% trans "Choose new Default" %}" /></p>
            </form>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

selenium_demo/templates/avatar/confirm_delete.html
{% extends "avatar/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <h2>{% trans "Please select the avatars that you would like to delete." %}</h2>
    {% if not avatars %}
        {% url 'avatar_change' as avatar_change_url %}
        <p>{% blocktrans %}You have no avatars to delete. Please <a href="{{ avatar_change_url }}">upload one</a> now.{% endblocktrans %}</p>
    {% else %}
        <form method="POST" action="{% url 'avatar_delete' %}">
            <ul>
                {{ delete_avatar_form.as_ul }}
            </ul>
            <p>{% csrf_token %}<input type="submit" value="{% trans "Delete These" %}" /></p>
        </form>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

selenium_demo/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}selenium_demo{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>

    <div class="header navbar">
      <div class="container">
        <a class="navbar-brand" href="/">selenium_demo</a>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container">
        
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 

selenium_demo/templates/pages/about.html
{% extends "base.html" %}

selenium_demo/templates/pages/home.html
{% extends "base.html" %}

selenium_demo/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->     
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <a class="btn btn-info" href="{% url 'avatar_change' %}">Avatar</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

selenium_demo/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

selenium_demo/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% load avatar_tags %}

{% block title %}Members{% endblock %}

{% block content %}

<div class="container">
    
  <div class="row">
    <div class="col-xs-12">
      <h2>Users</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="list-group">
          {% for user in user_list %}
            <a href="{% url 'users:detail' user.username %}" class="list-group-item">
              <h4 class="list-group-item-heading">{% avatar user %} {{ user.username }}</h4>
              <p class="list-group-item-text">{{ maker.tagline }}</p>
            </a>
          {% endfor %}
        
      </div>
    </div>
  </div>

</div>

{% endblock content %}